Pharmacy.Web/Models/ErrorViewModel.cs
namespace Pharmacy.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pharmacy.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pharmacy.Web.Models;
using System.Diagnostics;

namespace Pharmacy.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pharmacy.Web/Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Pharmacy.Core.DTOs;
using Pharmacy.Web.Services;

namespace Pharmacy.Web.Controllers
{
    public class MedicineController : Controller
    {
        private readonly MedicineApiService _medicineApiService;
        private readonly SuplierApiService _supplierApiService;

        public MedicineController(MedicineApiService medicineApiService, SuplierApiService supplierApiService)
        {
            _medicineApiService = medicineApiService;
            _supplierApiService = supplierApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _medicineApiService.GetMedicinesWithSuplierAsync());
        }

        public async Task<IActionResult> Save()
        {
            var supliersDto = await _supplierApiService.GetAllAsync();
            ViewBag.supliers = new SelectList(supliersDto, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(MedicineDto medicineDto)
        {
            if (ModelState.IsValid)
            {
                await _medicineApiService.SaveAsync(medicineDto);
                return RedirectToAction(nameof(Index));
            }

            var supliersDto = await _supplierApiService.GetAllAsync();
            ViewBag.supliers = new SelectList(supliersDto, "Id", "Name");
            return View();
        }

        //[ServiceFilter(typeof(NotFoundFilter<Product>))]
        public async Task<IActionResult> Update(int id)
        {
            var medicine = await _medicineApiService.GetByIdAsync(id);
            var suplierDto = await _supplierApiService.GetAllAsync();
            ViewBag.supliers = new SelectList(suplierDto, "Id", "Name", medicine.SuplierId);

            return View(medicine);
        }

        [HttpPost]
        public async Task<IActionResult> Update(MedicineDto medicineDto)
        {
            if (ModelState.IsValid)
            {
                await _medicineApiService.UpdateAsync(medicineDto);
                return RedirectToAction(nameof(Index));
            }

            var supliersDto = await _supplierApiService.GetAllAsync();
            ViewBag.supliers = new SelectList(supliersDto, "Id", "Name", medicineDto.SuplierId);

            return View(medicineDto);
        }

        public async Task<IActionResult> Remove(int id)
        {
            await _medicineApiService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Pharmacy.Web/Controllers/SuplierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Pharmacy.Core.DTOs;
using Pharmacy.Web.Services;

namespace Pharmacy.Web.Controllers
{
    public class SuplierController : Controller
    {
        private readonly SuplierApiService _suplierApiService;

        public SuplierController(SuplierApiService suplierApiService)
        {
            _suplierApiService = suplierApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _suplierApiService.GetAllAsync());
        }

        public async Task<IActionResult> Save()
        {           

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(SuplierDto suplierDto)
        {
            if (ModelState.IsValid)
            {
                await _suplierApiService.SaveAsync(suplierDto);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            return View(await _suplierApiService.GetByIdAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(SuplierDto suplierDto)
        {
            if (ModelState.IsValid)
            {
                await _suplierApiService.UpdateAsync(suplierDto);
                return RedirectToAction(nameof(Index));
            }

            return View(suplierDto);
        }

        public async Task<IActionResult> Remove(int id)
        {
            await _suplierApiService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Pharmacy.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pharmacy.Web/Views/Medicine/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<MedicineWithSuplierDto>

<h1>Medicines</h1>

<a class="btn btn-success" asp-controller="Medicine" asp-action="Save">Add Medicine</a>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Barcode</td>
            <td>Name</td>
            <td>Price</td>
            <td>Stock</td>
            <td>Suplier</td>
            <td>CreatedDate</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Barcode</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.Stock</td>
                <td>@item.Suplier.Name</td>
                <td>@item.CreatedDate</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Medicine" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="Medicine" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Pharmacy.Web/Views/Medicine/Save.cshtml
@{
    ViewData["Title"] = "Save";
}

@model MedicineCreateDto
<h1>Save Medicine</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Save" method="post" asp-controller="Medicine">

            <div class="form-group">
                <label asp-for="SuplierId"></label>
                <select asp-for="SuplierId" asp-items="ViewBag.supliers" class="form-control">
                    <option value="">Lütfen seçiniz</option>
                </select>
                <span asp-validation-for="SuplierId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Barcode"></label>
                <input asp-for="Barcode" class="form-control" />
                <span asp-validation-for="Barcode" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Stock"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Save" class="btn-primary" />

            </div>
        </form>
    </div>
</div>

Pharmacy.Web/Views/Medicine/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model MedicineDto
<h1>Update Medicine</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Update" method="post" asp-controller="Medicine">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SuplierId"></label>
                <select asp-for="SuplierId" asp-items="ViewBag.supliers" class="form-control">
                    <option value="">Please choose</option>
                </select>
                <span asp-validation-for="SuplierId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Barcode"></label>
                <input asp-for="Barcode" class="form-control" />
                <span asp-validation-for="Barcode" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Stock"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Update" class="btn-primary" />

            </div>
        </form>
    </div>
</div>

Pharmacy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pharmacy.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pharmacy.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Medicine" asp-action="Index">Pharmacy Warehouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Medicines</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suplier" asp-action="Index">Supliers</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pharmacy.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pharmacy.Web/Views/Suplier/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<SuplierDto>

<h1>Supliers</h1>

<a class="btn btn-success" asp-controller="Suplier" asp-action="Save">Add Suplier</a>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>TaxNumber</td>
            <td>CreatedDate</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.TaxNumber</td>
                <td>@item.CreatedDate</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Suplier" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="Suplier" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Pharmacy.Web/Views/Suplier/Save.cshtml
@{
    ViewData["Title"] = "Save";
}

@model SuplierCreateDto
<h1>Save Suplier</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Save" method="post" asp-controller="Suplier">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TaxNumber"></label>
                <input asp-for="TaxNumber" class="form-control" />
                <span asp-validation-for="TaxNumber" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Save" class="btn-primary" />

            </div>
        </form>
    </div>
</div>

Pharmacy.Web/Views/Suplier/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model SuplierDto
<h1>Update Suplier</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Update" method="post" asp-controller="Suplier">
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
                        
            <div class="form-group">
                <label asp-for="TaxNumber"></label>
                <input asp-for="TaxNumber" class="form-control" />
                <span asp-validation-for="TaxNumber" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Update" class="btn-primary" />

            </div>
        </form>
    </div>
</div>